[package]
name = "mockme"
version = "0.1.0"
authors = ["David Raifaizen <d-raif@hotmail.com>"]

[dependencies]
syn = { version = "0.11", features = ["full"] }
test_context = { path = "./test_context" }

[lib]
crate-type = ["proc-macro"]

